{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "03df2f24-3ecc-4b6c-adbc-9c6985f22c3f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dataset URL: https://www.kaggle.com/datasets/octopusteam/full-netflix-dataset\n",
      "Dataset downloaded and saved in C:\\Users\\Shashank Reddy\\Desktop\\Project\\Data\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "from kaggle.api.kaggle_api_extended import KaggleApi\n",
    "\n",
    "# Initialize Kaggle API\n",
    "api = KaggleApi()\n",
    "api.authenticate()\n",
    "\n",
    "# Fetch dataset and save to the data folder\n",
    "dataset_name = \"octopusteam/full-netflix-dataset\"  # Replace with your Kaggle dataset identifier\n",
    "save_path = r\"C:\\Users\\Shashank Reddy\\Desktop\\Project\\Data\"\n",
    "\n",
    "# Ensure the directory exists\n",
    "os.makedirs(save_path, exist_ok=True)\n",
    "\n",
    "# Download and unzip the dataset\n",
    "api.dataset_download_files(dataset_name, path=save_path, unzip=True)\n",
    "\n",
    "print(f\"Dataset downloaded and saved in {save_path}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "166b3f41-4cfe-46de-8c93-0811ee6c4fb5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importing essential packages\n",
    "import pandas as pd  # For data cleaning and manipulation\n",
    "import numpy as np  # For numerical computations\n",
    "\n",
    "# Visualization libraries\n",
    "import matplotlib.pyplot as plt  # For creating visualizations\n",
    "import seaborn as sns  # For enhanced statistical visualizations\n",
    "\n",
    "from sklearn.cluster import KMeans\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# Configuring visualization settings\n",
    "plt.style.use('ggplot')  # Set a popular plotting style\n",
    "sns.set_theme(style=\"whitegrid\")  # Set seaborn theme"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "0fc4e78d-650f-4473-a0e5-75cc2f07f7ad",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>type</th>\n",
       "      <th>genres</th>\n",
       "      <th>releaseYear</th>\n",
       "      <th>imdbId</th>\n",
       "      <th>imdbAverageRating</th>\n",
       "      <th>imdbNumVotes</th>\n",
       "      <th>availableCountries</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>The Fifth Element</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Adventure, Sci-Fi</td>\n",
       "      <td>1997.0</td>\n",
       "      <td>tt0119116</td>\n",
       "      <td>7.6</td>\n",
       "      <td>519811.0</td>\n",
       "      <td>AT, CH, DE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Kill Bill: Vol. 1</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Crime, Thriller</td>\n",
       "      <td>2003.0</td>\n",
       "      <td>tt0266697</td>\n",
       "      <td>8.2</td>\n",
       "      <td>1230147.0</td>\n",
       "      <td>AE, AL, AO, AT, AU, AZ, BG, BH, BY, CI, CM, CZ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jarhead</td>\n",
       "      <td>movie</td>\n",
       "      <td>Biography, Drama, War</td>\n",
       "      <td>2005.0</td>\n",
       "      <td>tt0418763</td>\n",
       "      <td>7.0</td>\n",
       "      <td>212975.0</td>\n",
       "      <td>AD, AE, AG, AO, BH, BM, BR, BS, BZ, CI, CM, CO...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Unforgiven</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Western</td>\n",
       "      <td>1992.0</td>\n",
       "      <td>tt0105695</td>\n",
       "      <td>8.2</td>\n",
       "      <td>447093.0</td>\n",
       "      <td>AU, BA, BG, CZ, HR, HU, MD, ME, MK, NZ, PL, RO...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Eternal Sunshine of the Spotless Mind</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Romance, Sci-Fi</td>\n",
       "      <td>2004.0</td>\n",
       "      <td>tt0338013</td>\n",
       "      <td>8.3</td>\n",
       "      <td>1115716.0</td>\n",
       "      <td>AD, AE, AG, AL, AO, AR, AU, AZ, BA, BB, BE, BG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20598</th>\n",
       "      <td>NaN</td>\n",
       "      <td>tv</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>KR</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20599</th>\n",
       "      <td>NaN</td>\n",
       "      <td>tv</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>KR</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20600</th>\n",
       "      <td>NaN</td>\n",
       "      <td>tv</td>\n",
       "      <td>Drama, Sci-Fi &amp; Fantasy</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>TH</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20601</th>\n",
       "      <td>NaN</td>\n",
       "      <td>tv</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2022.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>PH, SG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20602</th>\n",
       "      <td>NaN</td>\n",
       "      <td>tv</td>\n",
       "      <td>Animation</td>\n",
       "      <td>2014.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>JP</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>20603 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                       title   type  \\\n",
       "0                          The Fifth Element  movie   \n",
       "1                          Kill Bill: Vol. 1  movie   \n",
       "2                                    Jarhead  movie   \n",
       "3                                 Unforgiven  movie   \n",
       "4      Eternal Sunshine of the Spotless Mind  movie   \n",
       "...                                      ...    ...   \n",
       "20598                                    NaN     tv   \n",
       "20599                                    NaN     tv   \n",
       "20600                                    NaN     tv   \n",
       "20601                                    NaN     tv   \n",
       "20602                                    NaN     tv   \n",
       "\n",
       "                          genres  releaseYear     imdbId  imdbAverageRating  \\\n",
       "0      Action, Adventure, Sci-Fi       1997.0  tt0119116                7.6   \n",
       "1        Action, Crime, Thriller       2003.0  tt0266697                8.2   \n",
       "2          Biography, Drama, War       2005.0  tt0418763                7.0   \n",
       "3                 Drama, Western       1992.0  tt0105695                8.2   \n",
       "4         Drama, Romance, Sci-Fi       2004.0  tt0338013                8.3   \n",
       "...                          ...          ...        ...                ...   \n",
       "20598                        NaN       2024.0        NaN                NaN   \n",
       "20599                        NaN          NaN        NaN                NaN   \n",
       "20600    Drama, Sci-Fi & Fantasy       2024.0        NaN                NaN   \n",
       "20601                        NaN       2022.0        NaN                NaN   \n",
       "20602                  Animation       2014.0        NaN                NaN   \n",
       "\n",
       "       imdbNumVotes                                 availableCountries  \n",
       "0          519811.0                                         AT, CH, DE  \n",
       "1         1230147.0  AE, AL, AO, AT, AU, AZ, BG, BH, BY, CI, CM, CZ...  \n",
       "2          212975.0  AD, AE, AG, AO, BH, BM, BR, BS, BZ, CI, CM, CO...  \n",
       "3          447093.0  AU, BA, BG, CZ, HR, HU, MD, ME, MK, NZ, PL, RO...  \n",
       "4         1115716.0  AD, AE, AG, AL, AO, AR, AU, AZ, BA, BB, BE, BG...  \n",
       "...             ...                                                ...  \n",
       "20598           NaN                                                 KR  \n",
       "20599           NaN                                                 KR  \n",
       "20600           NaN                                                 TH  \n",
       "20601           NaN                                             PH, SG  \n",
       "20602           NaN                                                 JP  \n",
       "\n",
       "[20603 rows x 8 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv(r\"C:\\Users\\Shashank Reddy\\Desktop\\Project\\Data\\data.csv\")\n",
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1770c696-0e77-491c-98d3-822af40185a1",
   "metadata": {},
   "source": [
    "Data Cleaning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f997576a-72ec-408e-8e6d-b5f23dc72e52",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "title                  577\n",
      "type                     0\n",
      "genres                 318\n",
      "releaseYear             24\n",
      "imdbId                1438\n",
      "imdbAverageRating     1616\n",
      "imdbNumVotes          1616\n",
      "availableCountries       0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(df.isnull().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "10bebc26-7b60-4a4c-ad32-2d46d8f9ee03",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Index: 18987 entries, 0 to 20585\n",
      "Data columns (total 8 columns):\n",
      " #   Column              Non-Null Count  Dtype  \n",
      "---  ------              --------------  -----  \n",
      " 0   title               18987 non-null  object \n",
      " 1   type                18987 non-null  object \n",
      " 2   genres              18987 non-null  object \n",
      " 3   releaseYear         18987 non-null  float64\n",
      " 4   imdbId              18987 non-null  object \n",
      " 5   imdbAverageRating   18987 non-null  float64\n",
      " 6   imdbNumVotes        18987 non-null  float64\n",
      " 7   availableCountries  18987 non-null  object \n",
      "dtypes: float64(3), object(5)\n",
      "memory usage: 1.3+ MB\n",
      "None\n",
      "                                   title   type                     genres  \\\n",
      "0                      The Fifth Element  movie  Action, Adventure, Sci-Fi   \n",
      "1                      Kill Bill: Vol. 1  movie    Action, Crime, Thriller   \n",
      "2                                Jarhead  movie      Biography, Drama, War   \n",
      "3                             Unforgiven  movie             Drama, Western   \n",
      "4  Eternal Sunshine of the Spotless Mind  movie     Drama, Romance, Sci-Fi   \n",
      "\n",
      "   releaseYear     imdbId  imdbAverageRating  imdbNumVotes  \\\n",
      "0       1997.0  tt0119116                7.6      519811.0   \n",
      "1       2003.0  tt0266697                8.2     1230147.0   \n",
      "2       2005.0  tt0418763                7.0      212975.0   \n",
      "3       1992.0  tt0105695                8.2      447093.0   \n",
      "4       2004.0  tt0338013                8.3     1115716.0   \n",
      "\n",
      "                                  availableCountries  \n",
      "0                                         AT, CH, DE  \n",
      "1  AE, AL, AO, AT, AU, AZ, BG, BH, BY, CI, CM, CZ...  \n",
      "2  AD, AE, AG, AO, BH, BM, BR, BS, BZ, CI, CM, CO...  \n",
      "3  AU, BA, BG, CZ, HR, HU, MD, ME, MK, NZ, PL, RO...  \n",
      "4  AD, AE, AG, AL, AO, AR, AU, AZ, BA, BB, BE, BG...  \n"
     ]
    }
   ],
   "source": [
    "# Remove all rows with null values\n",
    "df = df.dropna()\n",
    "\n",
    "# Display the updated DataFrame info to confirm\n",
    "print(df.info())\n",
    "\n",
    "# Optionally display the first few rows to ensure it's cleaned\n",
    "print(df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "e512d9fd-eca6-47d4-8692-27f379c0353f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "title                 0\n",
      "type                  0\n",
      "genres                0\n",
      "releaseYear           0\n",
      "imdbId                0\n",
      "imdbAverageRating     0\n",
      "imdbNumVotes          0\n",
      "availableCountries    0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(df.isnull().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "3e3f03d1-c27b-485b-9013-efe2a1f43db9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of duplicate rows: 0\n"
     ]
    }
   ],
   "source": [
    "# Check for duplicates\n",
    "print(f\"Number of duplicate rows: {df.duplicated().sum()}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "3c647a8a-15ea-4629-b67d-5a9c56a44f19",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>type</th>\n",
       "      <th>genres</th>\n",
       "      <th>releaseYear</th>\n",
       "      <th>imdbId</th>\n",
       "      <th>imdbAverageRating</th>\n",
       "      <th>imdbNumVotes</th>\n",
       "      <th>availableCountries</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>The Fifth Element</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Adventure, Sci-Fi</td>\n",
       "      <td>1997.0</td>\n",
       "      <td>tt0119116</td>\n",
       "      <td>7.6</td>\n",
       "      <td>519811.0</td>\n",
       "      <td>AT, CH, DE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Kill Bill: Vol. 1</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Crime, Thriller</td>\n",
       "      <td>2003.0</td>\n",
       "      <td>tt0266697</td>\n",
       "      <td>8.2</td>\n",
       "      <td>1230147.0</td>\n",
       "      <td>AE, AL, AO, AT, AU, AZ, BG, BH, BY, CI, CM, CZ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jarhead</td>\n",
       "      <td>movie</td>\n",
       "      <td>Biography, Drama, War</td>\n",
       "      <td>2005.0</td>\n",
       "      <td>tt0418763</td>\n",
       "      <td>7.0</td>\n",
       "      <td>212975.0</td>\n",
       "      <td>AD, AE, AG, AO, BH, BM, BR, BS, BZ, CI, CM, CO...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Unforgiven</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Western</td>\n",
       "      <td>1992.0</td>\n",
       "      <td>tt0105695</td>\n",
       "      <td>8.2</td>\n",
       "      <td>447093.0</td>\n",
       "      <td>AU, BA, BG, CZ, HR, HU, MD, ME, MK, NZ, PL, RO...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Eternal Sunshine of the Spotless Mind</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Romance, Sci-Fi</td>\n",
       "      <td>2004.0</td>\n",
       "      <td>tt0338013</td>\n",
       "      <td>8.3</td>\n",
       "      <td>1115716.0</td>\n",
       "      <td>AD, AE, AG, AL, AO, AR, AU, AZ, BA, BB, BE, BG...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20570</th>\n",
       "      <td>S.E.R.E.G.</td>\n",
       "      <td>tv</td>\n",
       "      <td>Action</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>tt31242061</td>\n",
       "      <td>4.7</td>\n",
       "      <td>5525.0</td>\n",
       "      <td>HU</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20573</th>\n",
       "      <td>The Later Daters</td>\n",
       "      <td>tv</td>\n",
       "      <td>Reality-TV, Romance</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>tt34599590</td>\n",
       "      <td>6.9</td>\n",
       "      <td>320.0</td>\n",
       "      <td>AD, AE, AG, AL, AO, AR, AT, AU, AZ, BA, BB, BE...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20577</th>\n",
       "      <td>The Kings of Tupelo: A Southern Crime Saga</td>\n",
       "      <td>tv</td>\n",
       "      <td>Crime, Documentary</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>tt34682275</td>\n",
       "      <td>6.6</td>\n",
       "      <td>1279.0</td>\n",
       "      <td>AD, AE, AG, AL, AO, AR, AT, AU, AZ, BA, BB, BE...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20582</th>\n",
       "      <td>UniverXO Dabiz</td>\n",
       "      <td>tv</td>\n",
       "      <td>Documentary</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>tt34682889</td>\n",
       "      <td>5.8</td>\n",
       "      <td>80.0</td>\n",
       "      <td>AD, AE, AG, AL, AO, AR, AT, AU, AZ, BA, BB, BE...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20585</th>\n",
       "      <td>Das Boot - Die komplette TV-Serie</td>\n",
       "      <td>tv</td>\n",
       "      <td>Drama, War</td>\n",
       "      <td>1985.0</td>\n",
       "      <td>tt30970892</td>\n",
       "      <td>8.8</td>\n",
       "      <td>167.0</td>\n",
       "      <td>AT, CH, DE, LI</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>18987 rows × 8 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                            title   type  \\\n",
       "0                               The Fifth Element  movie   \n",
       "1                               Kill Bill: Vol. 1  movie   \n",
       "2                                         Jarhead  movie   \n",
       "3                                      Unforgiven  movie   \n",
       "4           Eternal Sunshine of the Spotless Mind  movie   \n",
       "...                                           ...    ...   \n",
       "20570                                  S.E.R.E.G.     tv   \n",
       "20573                            The Later Daters     tv   \n",
       "20577  The Kings of Tupelo: A Southern Crime Saga     tv   \n",
       "20582                              UniverXO Dabiz     tv   \n",
       "20585           Das Boot - Die komplette TV-Serie     tv   \n",
       "\n",
       "                          genres  releaseYear      imdbId  imdbAverageRating  \\\n",
       "0      Action, Adventure, Sci-Fi       1997.0   tt0119116                7.6   \n",
       "1        Action, Crime, Thriller       2003.0   tt0266697                8.2   \n",
       "2          Biography, Drama, War       2005.0   tt0418763                7.0   \n",
       "3                 Drama, Western       1992.0   tt0105695                8.2   \n",
       "4         Drama, Romance, Sci-Fi       2004.0   tt0338013                8.3   \n",
       "...                          ...          ...         ...                ...   \n",
       "20570                     Action       2024.0  tt31242061                4.7   \n",
       "20573        Reality-TV, Romance       2024.0  tt34599590                6.9   \n",
       "20577         Crime, Documentary       2024.0  tt34682275                6.6   \n",
       "20582                Documentary       2024.0  tt34682889                5.8   \n",
       "20585                 Drama, War       1985.0  tt30970892                8.8   \n",
       "\n",
       "       imdbNumVotes                                 availableCountries  \n",
       "0          519811.0                                         AT, CH, DE  \n",
       "1         1230147.0  AE, AL, AO, AT, AU, AZ, BG, BH, BY, CI, CM, CZ...  \n",
       "2          212975.0  AD, AE, AG, AO, BH, BM, BR, BS, BZ, CI, CM, CO...  \n",
       "3          447093.0  AU, BA, BG, CZ, HR, HU, MD, ME, MK, NZ, PL, RO...  \n",
       "4         1115716.0  AD, AE, AG, AL, AO, AR, AU, AZ, BA, BB, BE, BG...  \n",
       "...             ...                                                ...  \n",
       "20570        5525.0                                                 HU  \n",
       "20573         320.0  AD, AE, AG, AL, AO, AR, AT, AU, AZ, BA, BB, BE...  \n",
       "20577        1279.0  AD, AE, AG, AL, AO, AR, AT, AU, AZ, BA, BB, BE...  \n",
       "20582          80.0  AD, AE, AG, AL, AO, AR, AT, AU, AZ, BA, BB, BE...  \n",
       "20585         167.0                                     AT, CH, DE, LI  \n",
       "\n",
       "[18987 rows x 8 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "617a2af2-52a5-45b8-afa2-2e54a41cc35c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>type</th>\n",
       "      <th>genres</th>\n",
       "      <th>releaseYear</th>\n",
       "      <th>imdbAverageRating</th>\n",
       "      <th>imdbNumVotes</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>The Fifth Element</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Adventure, Sci-Fi</td>\n",
       "      <td>1997.0</td>\n",
       "      <td>7.6</td>\n",
       "      <td>519811.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Kill Bill: Vol. 1</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Crime, Thriller</td>\n",
       "      <td>2003.0</td>\n",
       "      <td>8.2</td>\n",
       "      <td>1230147.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jarhead</td>\n",
       "      <td>movie</td>\n",
       "      <td>Biography, Drama, War</td>\n",
       "      <td>2005.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>212975.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Unforgiven</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Western</td>\n",
       "      <td>1992.0</td>\n",
       "      <td>8.2</td>\n",
       "      <td>447093.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Eternal Sunshine of the Spotless Mind</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Romance, Sci-Fi</td>\n",
       "      <td>2004.0</td>\n",
       "      <td>8.3</td>\n",
       "      <td>1115716.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                   title   type                     genres  \\\n",
       "0                      The Fifth Element  movie  Action, Adventure, Sci-Fi   \n",
       "1                      Kill Bill: Vol. 1  movie    Action, Crime, Thriller   \n",
       "2                                Jarhead  movie      Biography, Drama, War   \n",
       "3                             Unforgiven  movie             Drama, Western   \n",
       "4  Eternal Sunshine of the Spotless Mind  movie     Drama, Romance, Sci-Fi   \n",
       "\n",
       "   releaseYear  imdbAverageRating  imdbNumVotes  \n",
       "0       1997.0                7.6      519811.0  \n",
       "1       2003.0                8.2     1230147.0  \n",
       "2       2005.0                7.0      212975.0  \n",
       "3       1992.0                8.2      447093.0  \n",
       "4       2004.0                8.3     1115716.0  "
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = df.drop(['availableCountries', 'imdbId'], axis=1)\n",
    "\n",
    "# Display the first few rows to confirm\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "92faa96f-e21e-48ac-ab36-809f245e0d5d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Title</th>\n",
       "      <th>Type</th>\n",
       "      <th>Genres</th>\n",
       "      <th>Year</th>\n",
       "      <th>Rating</th>\n",
       "      <th>Votes</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>The Fifth Element</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Adventure, Sci-Fi</td>\n",
       "      <td>1997.0</td>\n",
       "      <td>7.6</td>\n",
       "      <td>519811.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Kill Bill: Vol. 1</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Crime, Thriller</td>\n",
       "      <td>2003.0</td>\n",
       "      <td>8.2</td>\n",
       "      <td>1230147.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jarhead</td>\n",
       "      <td>movie</td>\n",
       "      <td>Biography, Drama, War</td>\n",
       "      <td>2005.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>212975.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Unforgiven</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Western</td>\n",
       "      <td>1992.0</td>\n",
       "      <td>8.2</td>\n",
       "      <td>447093.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Eternal Sunshine of the Spotless Mind</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Romance, Sci-Fi</td>\n",
       "      <td>2004.0</td>\n",
       "      <td>8.3</td>\n",
       "      <td>1115716.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20570</th>\n",
       "      <td>S.E.R.E.G.</td>\n",
       "      <td>tv</td>\n",
       "      <td>Action</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>4.7</td>\n",
       "      <td>5525.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20573</th>\n",
       "      <td>The Later Daters</td>\n",
       "      <td>tv</td>\n",
       "      <td>Reality-TV, Romance</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>6.9</td>\n",
       "      <td>320.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20577</th>\n",
       "      <td>The Kings of Tupelo: A Southern Crime Saga</td>\n",
       "      <td>tv</td>\n",
       "      <td>Crime, Documentary</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>6.6</td>\n",
       "      <td>1279.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20582</th>\n",
       "      <td>UniverXO Dabiz</td>\n",
       "      <td>tv</td>\n",
       "      <td>Documentary</td>\n",
       "      <td>2024.0</td>\n",
       "      <td>5.8</td>\n",
       "      <td>80.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20585</th>\n",
       "      <td>Das Boot - Die komplette TV-Serie</td>\n",
       "      <td>tv</td>\n",
       "      <td>Drama, War</td>\n",
       "      <td>1985.0</td>\n",
       "      <td>8.8</td>\n",
       "      <td>167.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>18987 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                            Title   Type  \\\n",
       "0                               The Fifth Element  movie   \n",
       "1                               Kill Bill: Vol. 1  movie   \n",
       "2                                         Jarhead  movie   \n",
       "3                                      Unforgiven  movie   \n",
       "4           Eternal Sunshine of the Spotless Mind  movie   \n",
       "...                                           ...    ...   \n",
       "20570                                  S.E.R.E.G.     tv   \n",
       "20573                            The Later Daters     tv   \n",
       "20577  The Kings of Tupelo: A Southern Crime Saga     tv   \n",
       "20582                              UniverXO Dabiz     tv   \n",
       "20585           Das Boot - Die komplette TV-Serie     tv   \n",
       "\n",
       "                          Genres    Year  Rating      Votes  \n",
       "0      Action, Adventure, Sci-Fi  1997.0     7.6   519811.0  \n",
       "1        Action, Crime, Thriller  2003.0     8.2  1230147.0  \n",
       "2          Biography, Drama, War  2005.0     7.0   212975.0  \n",
       "3                 Drama, Western  1992.0     8.2   447093.0  \n",
       "4         Drama, Romance, Sci-Fi  2004.0     8.3  1115716.0  \n",
       "...                          ...     ...     ...        ...  \n",
       "20570                     Action  2024.0     4.7     5525.0  \n",
       "20573        Reality-TV, Romance  2024.0     6.9      320.0  \n",
       "20577         Crime, Documentary  2024.0     6.6     1279.0  \n",
       "20582                Documentary  2024.0     5.8       80.0  \n",
       "20585                 Drama, War  1985.0     8.8      167.0  \n",
       "\n",
       "[18987 rows x 6 columns]"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Rename the columns for better readability\n",
    "df.columns = ['Title', 'Type', 'Genres', 'Year', 'Rating', 'Votes']\n",
    "\n",
    "# Display the updated DataFrame\n",
    "df\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "9697d6cf-ccd8-4f14-9862-5307a6e6b4b8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Title</th>\n",
       "      <th>Type</th>\n",
       "      <th>Genres</th>\n",
       "      <th>Year</th>\n",
       "      <th>Rating</th>\n",
       "      <th>Votes</th>\n",
       "      <th>Genre_1</th>\n",
       "      <th>Genre_2</th>\n",
       "      <th>Genre_3</th>\n",
       "      <th>Genre_4</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>The Fifth Element</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Adventure, Sci-Fi</td>\n",
       "      <td>1997.0</td>\n",
       "      <td>7.6</td>\n",
       "      <td>519811.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Adventure</td>\n",
       "      <td>Sci-Fi</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Kill Bill: Vol. 1</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Crime, Thriller</td>\n",
       "      <td>2003.0</td>\n",
       "      <td>8.2</td>\n",
       "      <td>1230147.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Crime</td>\n",
       "      <td>Thriller</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jarhead</td>\n",
       "      <td>movie</td>\n",
       "      <td>Biography, Drama, War</td>\n",
       "      <td>2005.0</td>\n",
       "      <td>7.0</td>\n",
       "      <td>212975.0</td>\n",
       "      <td>Biography</td>\n",
       "      <td>Drama</td>\n",
       "      <td>War</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Unforgiven</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Western</td>\n",
       "      <td>1992.0</td>\n",
       "      <td>8.2</td>\n",
       "      <td>447093.0</td>\n",
       "      <td>Drama</td>\n",
       "      <td>Western</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Eternal Sunshine of the Spotless Mind</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Romance, Sci-Fi</td>\n",
       "      <td>2004.0</td>\n",
       "      <td>8.3</td>\n",
       "      <td>1115716.0</td>\n",
       "      <td>Drama</td>\n",
       "      <td>Romance</td>\n",
       "      <td>Sci-Fi</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                   Title   Type                     Genres  \\\n",
       "0                      The Fifth Element  movie  Action, Adventure, Sci-Fi   \n",
       "1                      Kill Bill: Vol. 1  movie    Action, Crime, Thriller   \n",
       "2                                Jarhead  movie      Biography, Drama, War   \n",
       "3                             Unforgiven  movie             Drama, Western   \n",
       "4  Eternal Sunshine of the Spotless Mind  movie     Drama, Romance, Sci-Fi   \n",
       "\n",
       "     Year  Rating      Votes    Genre_1    Genre_2   Genre_3 Genre_4  \n",
       "0  1997.0     7.6   519811.0     Action  Adventure    Sci-Fi    None  \n",
       "1  2003.0     8.2  1230147.0     Action      Crime  Thriller    None  \n",
       "2  2005.0     7.0   212975.0  Biography      Drama       War    None  \n",
       "3  1992.0     8.2   447093.0      Drama    Western      None    None  \n",
       "4  2004.0     8.3  1115716.0      Drama    Romance    Sci-Fi    None  "
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Split the 'Genres' column into multiple columns\n",
    "genres_split = df['Genres'].str.split(', ', expand=True)\n",
    "\n",
    "# Rename the new columns for clarity\n",
    "genres_split.columns = [f'Genre_{i+1}' for i in range(genres_split.shape[1])]\n",
    "\n",
    "# Combine the original DataFrame with the new genre columns\n",
    "df = pd.concat([df, genres_split], axis=1)\n",
    "\n",
    "# Drop the original 'Genres' column (optional)\n",
    "# df.drop('Genres', axis=1, inplace=True)\n",
    "\n",
    "# Display the updated DataFrame\n",
    "df.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "701dd1c9-6305-4380-bb6f-e704ed664773",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Title</th>\n",
       "      <th>Type</th>\n",
       "      <th>Genres</th>\n",
       "      <th>Year</th>\n",
       "      <th>Rating</th>\n",
       "      <th>Votes</th>\n",
       "      <th>Genre_1</th>\n",
       "      <th>Genre_2</th>\n",
       "      <th>Genre_3</th>\n",
       "      <th>Genre_4</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>The Fifth Element</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Adventure, Sci-Fi</td>\n",
       "      <td>1997</td>\n",
       "      <td>7.6</td>\n",
       "      <td>519811.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Adventure</td>\n",
       "      <td>Sci-Fi</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Kill Bill: Vol. 1</td>\n",
       "      <td>movie</td>\n",
       "      <td>Action, Crime, Thriller</td>\n",
       "      <td>2003</td>\n",
       "      <td>8.2</td>\n",
       "      <td>1230147.0</td>\n",
       "      <td>Action</td>\n",
       "      <td>Crime</td>\n",
       "      <td>Thriller</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jarhead</td>\n",
       "      <td>movie</td>\n",
       "      <td>Biography, Drama, War</td>\n",
       "      <td>2005</td>\n",
       "      <td>7.0</td>\n",
       "      <td>212975.0</td>\n",
       "      <td>Biography</td>\n",
       "      <td>Drama</td>\n",
       "      <td>War</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Unforgiven</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Western</td>\n",
       "      <td>1992</td>\n",
       "      <td>8.2</td>\n",
       "      <td>447093.0</td>\n",
       "      <td>Drama</td>\n",
       "      <td>Western</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Eternal Sunshine of the Spotless Mind</td>\n",
       "      <td>movie</td>\n",
       "      <td>Drama, Romance, Sci-Fi</td>\n",
       "      <td>2004</td>\n",
       "      <td>8.3</td>\n",
       "      <td>1115716.0</td>\n",
       "      <td>Drama</td>\n",
       "      <td>Romance</td>\n",
       "      <td>Sci-Fi</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                   Title   Type                     Genres  \\\n",
       "0                      The Fifth Element  movie  Action, Adventure, Sci-Fi   \n",
       "1                      Kill Bill: Vol. 1  movie    Action, Crime, Thriller   \n",
       "2                                Jarhead  movie      Biography, Drama, War   \n",
       "3                             Unforgiven  movie             Drama, Western   \n",
       "4  Eternal Sunshine of the Spotless Mind  movie     Drama, Romance, Sci-Fi   \n",
       "\n",
       "   Year  Rating      Votes    Genre_1    Genre_2   Genre_3 Genre_4  \n",
       "0  1997     7.6   519811.0     Action  Adventure    Sci-Fi    None  \n",
       "1  2003     8.2  1230147.0     Action      Crime  Thriller    None  \n",
       "2  2005     7.0   212975.0  Biography      Drama       War    None  \n",
       "3  1992     8.2   447093.0      Drama    Western      None    None  \n",
       "4  2004     8.3  1115716.0      Drama    Romance    Sci-Fi    None  "
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Convert the 'Year' column to integer\n",
    "df['Year'] = df['Year'].astype('Int64')\n",
    "\n",
    "# Display the updated DataFrame\n",
    "df.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "cdeea03f-23e2-4333-9a8f-a441db6a1fc6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Transformed dataset saved successfully at C:\\Users\\Shashank Reddy\\Desktop\\Project\\Data\\transformed_dataset.csv\n"
     ]
    }
   ],
   "source": [
    "# Define the path for saving the transformed dataset\n",
    "save_path = r\"C:\\Users\\Shashank Reddy\\Desktop\\Project\\Data\\transformed_dataset.csv\"\n",
    "\n",
    "# Save the dataset to the specified folder\n",
    "df.to_csv(save_path, index=False)\n",
    "\n",
    "# Optional: Save as Excel\n",
    "# save_path_excel = r\"C:\\Users\\Shashank Reddy\\Desktop\\Project\\Data\\transformed_dataset.xlsx\"\n",
    "# df.to_excel(save_path_excel, index=False)\n",
    "\n",
    "print(f\"Transformed dataset saved successfully at {save_path}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ad3e31a-a641-47d1-a5eb-d0d5aacfdf5c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
